# Generated by Django 2.1 on 2022-06-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20220524_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_image', models.ImageField(blank=True, null=True, upload_to='uploads/pics')),
                ('services_title', models.CharField(max_length=25)),
                ('services_body', models.TextField()),
            ],
        ),
    ]
